ALTER TABLE "Source" ADD COLUMN "lastFetchedAt" DATETIME;
ALTER TABLE "Source" ADD COLUMN "lastStatus" TEXT NOT NULL DEFAULT 'skipped';
ALTER TABLE "Source" ADD COLUMN "lastError" TEXT;
ALTER TABLE "Source" ADD COLUMN "fetchedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Source" ADD COLUMN "acceptedCount" INTEGER NOT NULL DEFAULT 0;
